# Generated by Django 4.2.1 on 2023-06-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ingredientsrecipe',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3, verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
