# Generated by Django 4.2.1 on 2023-06-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientsrecipe',
            old_name='quantity',
            new_name='amount',
        ),
    ]
