# Generated by Django 4.2.1 on 2023-07-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_ingredientsrecipe_unique_ingredient_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientsrecipe',
            name='unique_ingredient_recipe',
        ),
        migrations.RemoveConstraint(
            model_name='tagrecipe',
            name='unique_tag_recipe',
        ),
        migrations.AddConstraint(
            model_name='ingredientsrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredients'), name='unique_ingredient_recipe'),
        ),
        migrations.AddConstraint(
            model_name='tagrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'tag'), name='unique_tag_recipe'),
        ),
    ]
